# Form implementation generated from reading ui file 'layout2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: cadetblue; color: black;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet("color: antiquewhite;\n"
"font-size: 24px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_key = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.input_key.setMaximumSize(QtCore.QSize(16777215, 20))
        self.input_key.setStyleSheet("background-color: white; margin: 0 auto;")
        self.input_key.setObjectName("input_key")
        self.verticalLayout.addWidget(self.input_key)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setStyleSheet("color: antiquewhite;\n"
"font-size: 24px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_cleartext = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.input_cleartext.setAutoFillBackground(False)
        self.input_cleartext.setStyleSheet("background-color: white;")
        self.input_cleartext.setPlainText("")
        self.input_cleartext.setObjectName("input_cleartext")
        self.verticalLayout.addWidget(self.input_cleartext)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.btn_cipher = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_cipher.setStyleSheet("background-color: lightblue;")
        self.btn_cipher.setObjectName("btn_cipher")
        self.horizontalLayout.addWidget(self.btn_cipher)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("color: antiquewhite;\n"
"font-size: 24px;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.output_encrypted = QtWidgets.QLabel(parent=self.centralwidget)
        self.output_encrypted.setStyleSheet("color: aliceblue;\n"
"font-size: 18px;\n"
"border: 5px solid antiquewhite;\n"
"border-radius: 15px;\n"
"padding: 10px;")
        self.output_encrypted.setText("")
        self.output_encrypted.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.output_encrypted.setObjectName("output_encrypted")
        self.verticalLayout_2.addWidget(self.output_encrypted)
        self.btn_save_to_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_save_to_file.setStyleSheet("background-color: lightblue;")
        self.btn_save_to_file.setObjectName("btn_save_to_file")
        self.verticalLayout_2.addWidget(self.btn_save_to_file)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Szyfrowanie. Wykonane przez 8-22403"))
        self.label.setText(_translate("MainWindow", "Podaj wartość klucza"))
        self.label_2.setText(_translate("MainWindow", "Podaj tekst"))
        self.btn_cipher.setText(_translate("MainWindow", "Zaszyfruj"))
        self.label_3.setText(_translate("MainWindow", "Tekst zaszyfrowany"))
        self.btn_save_to_file.setText(_translate("MainWindow", "Zapisz szyfr w pliku"))
